# Generated by Django 4.2.6 on 2023-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.CharField(blank=True, choices=[('web development', 'Web Development'), ('automation', 'Automation'), ('artifiacl intelligence', 'Artifiacl Intelligence'), ('cyber security', 'Cyber Security')], max_length=100, null=True)),
                ('langsymbol', models.ImageField(blank=True, null=True, upload_to='lang_symbol')),
                ('cert', models.ImageField(blank=True, null=True, upload_to='certs')),
            ],
        ),
    ]
