# Generated by Django 4.2.6 on 2023-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0004_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='instalation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
