# Generated by Django 4.2.6 on 2023-12-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0005_project_features_project_frameworks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='instalation',
            new_name='installation',
        ),
    ]
