# Generated by Django 4.2.7 on 2023-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0006_rename_instalation_project_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frameworks',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
